/******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/

'use strict';

const fs = require('fs');
const express = require('express');
const moment = require('moment');
const dateChecker = require('./dateChecker');
const app = express();

app.get('/time/:timestamp', function (request, response) {

    const input = request.params;
    let unixTime;
    let naturalTime;

    console.log(moment.unix(input["timestamp"]).format('LL'));
    if(dateChecker.verifyTimestamp(Number(input["timestamp"]))){
            unixTime = input["timestamp"];
            naturalTime = dateChecker.humanizeDate(input["timestamp"]);

    }
    else if (dateChecker.isDateValid(input["timestamp"])){
            unixTime = dateChecker.unixifyDate(input["timestamp"]).toString();
            naturalTime = input["timestamp"];

    }
    else {
        unixTime = null;
        naturalTime = null;
    }

    const responseBody = {
        'natural': naturalTime,
        'unix': unixTime
    };
    response.json(responseBody);
});
app.listen(3000, function (err, data) {
    if (err) {
        throw err
    }
    console.log('Node.js listening on  3000 ... ');
});
