/** ****************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ************************************************** */

const express = require('express');
const dateChecker = require('./dateChecker');

const app = express();

app.get('/time/:timestamp', (request, response) => {
  const input = request.params;
  let unixTime;
  let naturalTime;


  if (dateChecker.verifyTimestamp(Number(input.timestamp))) {
    unixTime = input.timestamp;
    naturalTime = dateChecker.humanizeDate(input.timestamp);
  } else if (dateChecker.isDateValid(input.timestamp)) {
    unixTime = dateChecker.unixifyDate(input.timestamp).toString();
    naturalTime = input.timestamp;
  } else {
    unixTime = null;
    naturalTime = null;
  }

  const responseBody = {
    natural: naturalTime,
    unix: unixTime,
  };
  response.json(responseBody).end();
});

app.route('/')
  .get((req, res) => {
    res.sendFile(`${process.cwd()}/views/index.html`);
  });

app.listen(3000, (err) => {
  if (err) {
    throw err;
  }
});
module.exports = app;
